# ASDF use ansible community version
# https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-community-changelogs
[tools]
pipx = "latest"
ansible = "latest"
python = "3.13.1"
ls-lint = "latest"
java = "latest"

[tasks.compare-dotfiles]
description = "Compare provisioned files with actual home directory"
run = "scripts/compare-dotfiles.sh"
