# ASDF use ansible community version
# https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-community-changelogs
[tools]
pipx = "latest"
ansible = "latest"
python = "3.13.7"
