
- name: ADSF install plugins
  command: "bash -lc 'asdf plugin add {{ item.name }} {{ item.repository | default() }}'"
  args:
    creates: "{{ ansible_env.HOME }}/.asdf/plugins/{{ item.name }}"
  loop: "{{ asdf_plugins }}"
  when: asdf_plugins|length > 0
  ignore_errors: True
  tags:
    - asdf

- name: Install pip packages
  pip:
    executable:  "{{ ansible_env.HOME }}/.pyenv/shims/pip"
    name: "{{ item }}"
  loop: "{{ pip_packages }}"
